### ISSUE TITLE
Darkened tiles using gs tile

### ISSUE THREAD

**Issue by Youthanasia5** [datapink/neat-EO#12]
Hi!

I used `gs tile` with the following command `gs tile --zoom 10 --rasters rs  --out ds`
When I opened the tiles I noticed that tiles is very darkened. In QGIS, I was able to see the data when I increased the contrast and brightness.
So, how will this affect to the training and prediction process?

**Comment by ocourtin** [comment]
Hi,

As there is no `gs tile` i assume you used `neo tile` ?

And if you need to change contrast and brightness in order to human see something with QGIS,
you surely have to do it too before tiling...
