### ISSUE TITLE
Issue running tutorial on neo rasterize

### ISSUE THREAD

**Issue by arruga** [datapink/neat-EO#15]
Hi,
When I run

neo rasterize --geojson train/*/*-labels/*.geojson --type Building --buffer -0.25 --cover train/cover.csv --out train/labels

I get the following error:

neo rasterize - Compute spatial index with 12 workers
  0%|                                             | 0/7308 [00:00<?, ?feature/s]
ERROR: A process in the process pool was terminated abruptly while the future was running or pending.

A previous execution of neo rasterize failed because libgeos_c.so was not found in /usr/lib and it seems that some garbage remains somewhere. Restarting the computer or creating again the train folder didn't solved the issue.
My configuration according neo info is:

========================================
Neat-EO.pink: 0.7.3
========================================
Linux   Ubuntu 18.04.4 LTS
Python  3.6.9
Torch   1.4.0
OpenCV  4.2.0
GDAL    2.4.3
Cuda    10.1
Cudnn   7603
NCCL    2408
========================================
RAM     64Go
CPUs    32
========================================
VRAM    48Go
GPUs    2
 - Quadro RTX 6000
 - Quadro RTX 6000
========================================
HTTPD   Running
========================================

**Comment by ocourtin** [comment]
Hi @arruga 

I've just check back with both 0.7.3 and master, and both versions are OK with neo rasterize tutorial command line.
However, this tutorial command is not the same as the one you quoted: 

`neo rasterize --geojson train/*/*-labels/*.geojson --type Building --buffer -0.25 --cover train/cover.csv --out train/labels`


But i can't reproduce the behaviour you referring to (even with your own quote).
i suggest to uninstall and reinstall:
`pip3 uninstall neat-EO`
`pip3 install neat-EO==0.7.3`

(As geos lib used in neat-EO, is the one provided by rasterio pip wheel, and not the system one)

HTH,

**Comment by ocourtin** [comment]
@arruga 

Finally, i can reproduce it,
thanks for the report,
i investigate on it.

**Comment by ocourtin** [comment]
Looks like it's related to shapely version (i.e works with prior 1.6.x but crash with new 1.7.x)
Could you perform a `pip3 install shapely==1.6.4` and retry ?

**Comment by ocourtin** [comment]
For the record, on a fresh server install (cf https://github.com/datapink/neat-EO#with-ubuntu-1910-from-scratch) using shapely 1.7.0 is OK.

So seems related less to the shapely version, than to shapely upgrade.

As an immediate workaround, i will remove from the tutorial the `--buffer -0.25` option, 
to avoid shapely calls. And will also explore alternate PyGeos (as it claims to also be more efficient)

**Comment by arruga** [comment]
Yes! With shapely 1.6.4 it works. Thank you very much
